In [1]:
import numpy as np

In [4]:
a = np.arange(0,15,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [7]:
a = np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
a = np.random.rand(5)
a

array([0.74086969, 0.89311117, 0.0036829 , 0.91720877, 0.94178983])

In [9]:
a = np.random.randn(5)
a

array([-0.17838818, -0.59979373,  0.61782098,  0.2450707 ,  0.77096741])

In [10]:
a = np.random.randint(0,10,5)
a

array([5, 7, 9, 4, 5])

In [14]:
a.dtype
a.shape
a.ndim

1

## 索引与切片

In [15]:
a[1:3]

array([7, 9])

In [16]:
a[1:]-a[:-1]

array([ 2,  2, -5,  1])

In [21]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [18]:
b.shape

(3, 3)

In [19]:
b[1,2]

6

In [20]:
b[:,1]

array([2, 5, 8])

In [22]:
b[1,1:3]

array([5, 6])

In [24]:
b[::2,::2]
# 使用引用机制

array([[ 1,  3],
       [ 7,  9],
       [13, 15]])

In [25]:
mask = np.array([0,1,1,0,0],dtype=bool)
a[mask]

array([7, 9])

In [27]:
b[(0,1,2),(1,2,0)]

array([2, 6, 7])

In [29]:
a[np.where(a>5)]

array([7, 9])

## 类型转换

In [34]:
c = np.array([1,2,3.53,4,5],dtype=int)
c.astype(float)     # 转换数据类型

array([1., 2., 3., 4., 5.])

## 函数

In [35]:
np.argsort(a)       # 返回排序后的索引

array([3, 0, 4, 1, 2], dtype=int64)

In [36]:
a.sum()

30

In [38]:
a.mean()

6.0

In [39]:
a.std()

1.7888543819998317

## 相关系数矩阵

In [40]:
ab= np.array([[2,3],[5,6],[7,8]])
bc = np.array([[1,2],[3,4],[5,6]])
np.cov(ab,bc)       # 协方差

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [43]:
cd = np.arange(1,40).reshape(13,3)
cd

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

In [45]:
cd.transpose()      # 转置
cd.T

array([[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37],
       [ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39]])

## 数据连接

In [48]:
z = np.concatenate((ab,bc))      # 拼接
z

array([[2, 3],
       [5, 6],
       [7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [50]:
zc = np.array([ab,bc])
zc

array([[[2, 3],
        [5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [51]:
np.vstack((ab,bc))      # 垂直拼接

array([[2, 3],
       [5, 6],
       [7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [52]:
np.hstack((ab,bc))      # 水平拼接

array([[2, 3, 1, 2],
       [5, 6, 3, 4],
       [7, 8, 5, 6]])

In [54]:
np.dstack((ab,bc))      # 深度拼接

array([[[2, 1],
        [3, 2]],

       [[5, 3],
        [6, 4]],

       [[7, 5],
        [8, 6]]])

In [55]:
aa = np.arange(-12,10)

In [57]:
np.abs(aa)      # 绝对值

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9])

In [58]:
np.exp(aa)      # 指数

array([6.14421235e-06, 1.67017008e-05, 4.53999298e-05, 1.23409804e-04,
       3.35462628e-04, 9.11881966e-04, 2.47875218e-03, 6.73794700e-03,
       1.83156389e-02, 4.97870684e-02, 1.35335283e-01, 3.67879441e-01,
       1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [60]:
np.median(aa)       # 中位数

-1.5

In [61]:
np.cumsum(aa)       # 累加

array([-12, -23, -33, -42, -50, -57, -63, -68, -72, -75, -77, -78, -78,
       -77, -75, -72, -68, -63, -57, -50, -42, -33])